TEAM-D-Okome/nagano_cake

config/initializers/devise.rb, config/locales/devise.en.yml
deviseを導入しました。developブランチへのマージをお願いいたします。
=> Add devise

config/application.rb, config/locales/ja.yml
enum_helpに使用するファイルの作成とapplication.rbの編集を行いました。
=> Feature add enum help

db/migrate/20230417053816_create_active_storage_tables.active_storage.rb, db/schema.rb
ActiveStorageの導入をしました。
モデルに記述を追加する以降がまだできないので、それまでの手順だけ終わらせました。
=> Feature add active storage

Gemfile, Gemfile.lock, app/views/kaminari/_first_page.html.erb, app/views/kaminari/_gap.html.erb, app/views/kaminari/_last_page.html.erb, app/views/kaminari/_next_page.html.erb, app/views/kaminari/_page.html.erb, app/views/kaminari/_paginator.html.erb, app/views/kaminari/_prev_page.html.erb, config/initializers/kaminari_config.rb
=> add kaminari

app/javascript/packs/application.js, app/javascript/stylesheets/application.scss, app/views/layouts/application.html.erb, config/webpack/environment.js, package.json, yarn.lock
BootstrapとFontAwesomeの導入しました。
確認お願いします。
=> Add Bootstrap & FontAwesome

app/models/customer.rb, config/routes.rb, db/migrate/20230417063026_devise_create_customers.rb, db/schema.rb, test/fixtures/customers.yml, test/models/customer_test.rb
=> Feature add devise customer

app/models/admin.rb, config/routes.rb, db/migrate/20230417064729_devise_create_admins.rb, db/schema.rb, test/fixtures/admins.yml, test/models/admin_test.rb
=> Add deviseAdmin2

app/models/delivery_address.rb, db/migrate/20230417071506_create_delivery_addresses.rb, test/fixtures/delivery_addresses.yml, test/models/delivery_address_test.rb
=> Feature add model delivery address2

app/models/genre.rb, db/migrate/20230417072020_create_genres.rb, test/fixtures/genres.yml, test/models/genre_test.rb
=> Feature add model genre

app/controllers/admin/confirmations_controller.rb, app/controllers/admin/omniauth_callbacks_controller.rb, app/controllers/admin/passwords_controller.rb, app/controllers/admin/registrations_controller.rb, app/controllers/admin/sessions_controller.rb, app/controllers/admin/unlocks_controller.rb, app/views/admin/confirmations/new.html.erb, app/views/admin/mailer/confirmation_instructions.html.erb, app/views/admin/mailer/email_changed.html.erb, app/views/admin/mailer/password_change.html.erb, app/views/admin/mailer/reset_password_instructions.html.erb, app/views/admin/mailer/unlock_instructions.html.erb, app/views/admin/passwords/edit.html.erb, app/views/admin/passwords/new.html.erb, app/views/admin/registrations/edit.html.erb, app/views/admin/registrations/new.html.erb, app/views/admin/sessions/new.html.erb, app/views/admin/shared/_error_messages.html.erb, app/views/admin/shared/_links.html.erb, app/views/admin/unlocks/new.html.erb, config/routes.rb
全てカリキュラム「実装ヒント・複数権限でのDevise使用・退会機能実装」を見て行いました。
[rails g devise:controllers admin]を実行。
[rails g devise:views admins]を実行。ファイル名を「admins」から「admin」に変更。
「app/views/admin/sessions/new.html.erb」の
「<%= render "admins/shared/links" %>」を「<%= render "admin/shared/links" %>」に変更。
「config/routes.rb」のルーティングの記述を変更。
=> Add AdminコントローラとViewの作成ルーティングも記述

app/models/order.rb, db/migrate/20230417081444_create_orders.rb, test/fixtures/orders.yml, test/models/order_test.rb
注文モデル作成しました。
カート内商品同様has_one_attached :imageは話し合いの上決めるため記述しておりません。
=> add-model order

app/models/cart_item.rb, db/migrate/20230417072014_create_cart_items.rb, test/fixtures/cart_items.yml, test/models/cart_item_test.rb
カート内商品モデルを作成しました。
モデルファイルへのhas_one_attached :imageは皆で確認してからにしようと思っているので記述しておりません。
=> add-model cart_item

app/controllers/public/items_controller.rb
public/items controllerに記述しました。
=> Feature public/items controller

app/controllers/public/registrations_controller.rb
registrations controllerに記述を追加しました
=> Feature add registrations controller

app/controllers/public/sessions_controller.rb
=> Feature add sessions controller

app/controllers/public/homes_controller.rb
=> homesコントローラーに記述を追加

app/controllers/public/customers_controller.rb
custmers controller に記述を追加しました
=> Feature add custmers controller

app/controllers/public/delivery_addresses_controller.rb
delivery addresses controller に記述を追加しました
=> Feature add delivery addresses controller

app/controllers/public/homes_controller.rb
Reverts TEAM-D-Okome/nagano_cake#26
=> Revert "homesコントローラーに記述を追加"

app/controllers/admin/homes_controller.rb
=> Feature add homes controller2

app/controllers/admin/customers_controller.rb, db/schema.rb
[admin_customers]のコントローラを記述しました。
index-顧客一覧
show-顧客詳細
edit-顧客編集
update-顧客更新
となっております。
=> Feature admin controller

app/controllers/admin/genres_controller.rb
[admin_genres]のコントローラを記述しました。
index-ジャンル管理画面(一覧・追加を兼ねる)
new-ジャンルデータ新規登録
edit-ジャンル編集
update-ジャンルデータ更新
となっております。
=> Add admin/genres_controllerに記述を追加

app/controllers/admin/customers_controller.rb, db/schema.rb
Reverts TEAM-D-Okome/nagano_cake#20
=> Revert "Feature admin controller"

app/controllers/admin/orders_controller.rb
[admin/orders]のコントローラを記述しました。
index-注文履歴一覧ページも必要だと思いファイルを追加しています。
index-注文履歴一覧
show-注文詳細
update-注文履歴更新
になっています。
=> Add admin/order_controllerに記述を追加indexページが必要と思い追加

app/controllers/public/cart_items_controller.rb
public/cart items controllerに記述しました。
=> Feature public/cart items controller

app/controllers/admin/order_items_controller.rb
[admin/order_items]のコントローラを記述しました。
update-製作ステータス更新
となっております。
=> Add admin/order_items_controllerに記述を追加

app/controllers/admin/items_controller.rb
[admin_items]のコントローラを記述しました。
index-商品一覧
new-新規登録された商品表示
create-商品新規登録
show-商品詳細
edit-商品情報編集
update-商品情報更新
となっております。
=> Add admin/items_controllerに記述を追加

app/controllers/public/orders_controller.rb
public/orders_controllerに記述を加えました。
時間かかって申し訳ない。
=> Add public/OrdersControllerに記述を追加

app/views/public/registrations/new.html.erb, app/views/public/sessions/new.html.erb, config/routes.rb
=> Feature add view registration

app/views/admin/homes/top.html.erb, config/webpack/environment.js, db/migrate/20230417090351_drop_table_notifications.rb
※こちらのマージは本日(4/19水)、一番最後にしていただけるとありがたいです。
admin/homes/topを編集しました。
=> Add admin/homes/topを編集、Fix Bootstrap読み込み直し　Remove dropマイグレーションファイルを削除

app/controllers/application_controller.rb, app/views/admin/shared/_links.html.erb, app/views/layouts/_footer.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, app/views/public/shared/_links.html.erb, config/routes.rb, config/webpack/environment.js, db/migrate/20230417090351_drop_table_notifications.rb, db/seeds.rb
※こちらのマージは明日、一番最後にしていただけるとありがたいです。
理由1・downさせた[dorp~]のマイグレーションファイルの削除を行っているから。
理由2・Bootstrapは反映されたが管理者ログインができないため、一番最後にマージ後、
問題解決を手伝っていただきたいから。できなければメンターに質問したいため最後にしたいです。
追加したもの
headerとfooterの部分テンプレートファイルを作成。記述も加えました。
seeds.rbに記述を追加、「rails db:seed」も実行。しかし、ログインできないのでコメントアウトしました。
削除したもの
[_dorp~]というマイグレーションファイル。
adminとpublicの_links.html.erbの不要な記述を削除。(カリキュラム実装のヒント参考)
修正したもの
headerとfooterの背景色と文字色を変更。
ルーティングのadmin ordersにindexを追記。
=> Feature header and footer

app/controllers/application_controller.rb, app/controllers/public/customers_controller.rb, app/controllers/public/registrations_controller.rb, app/views/layouts/_header.html.erb, db/seeds.rb
=> seedファイル追加

app/views/admin/items/index.html.erb
Add admin items index 商品一覧ページを作成しました。
=> Add admin items index 商品一覧ページを作成

app/controllers/public/customers_controller.rb, app/controllers/public/sessions_controller.rb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, app/views/public/customers/unsubscribe.html.erb, app/views/public/registrations/new.html.erb, app/views/public/sessions/new.html.erb, config/routes.rb
viewの作成に伴い、以下のファイルを修正しました。
app/controllers/public/customers_controller.rb
・noticeメッセージを追加しました
app/controllers/public/sessions_controller.rb
・noticeメッセージを追加しました
app/views/public/registrations/new.html.erb
・emailと住所の入力フィールドのサイズを変更しました
app/views/public/sessions/new.html.erb
・route.rbファイルの変更に伴い、パス名を変更しました。（route.rbの変更内容の詳細は下記）
config/routes.rb
・独自のアクション（customersのunsubscribe,withdrawalとordersのconfirm,finish）のルーティングの指定が間違っていたので修正しました。（参考サイト： https://qiita.com/minhee/items/45fa84ac90017dbdcfa9 ）
=> Feature add view customer

app/views/public/customers/edit.html.erb, app/views/public/customers/unsubscribe.html.erb, app/views/public/homes/top.html.erb
トップページに最新四件の商品が表示されるように修正しました
また、退会時の処理をunsubscribe画面の退会するボタンを押したときに確認ダイアログが出るように変更しました。
=> topとcustomer/editのviewを修正

app/controllers/admin/customers_controller.rb, app/views/admin/customers/_error.html.erb, app/views/admin/customers/edit.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb
Add admin顧客ページ　index show edit errorメッセージのための共通化ファイル作成しまた。
=> Feature admin views customers index show edit

app/views/admin/orders/index.html.erb, app/views/admin/orders/show.html.erb
Add admin　ordersのindexを作成しました。
showは他のページをマージしてから出ないと、作成が難しいので
後回しにします。
=> Feature admin views orders index show

app/controllers/public/delivery_addresses_controller.rb, app/views/public/delivery_addresses/edit.html.erb, app/views/public/delivery_addresses/index.html.erb
=> Feature add view delivery address

app/views/public/orders/index.html.erb
=> Add ordersのviewのindexを作成

app/views/public/orders/comfirm.html.erb, app/views/public/orders/complete.html.erb
Add orders view confirmとcompleteを作成しました。
正しく動作するかはカートアイテムをマージしてから確認が必要です。
=> Add orders view confirmとcompleteを作成、正しく動作するかはカートアイテムをマージしてから確認が必要

app/controllers/admin/orders_controller.rb, app/views/public/orders/new.html.erb, app/views/public/orders/show.html.erb, db/migrate/20230417081444_create_orders.rb
Add ordersのshowとnewを作成しました。
正しく動作するかはカートアイテムをマージした際に確認する必要があります。
=> Add ordersのshowとnewを作成、正しく動作するかはカートアイテムをマージした際に確認する

app/views/public/registrations/new.html.erb, app/views/public/sessions/new.html.erb, db/seeds.rb
=> #62 issueの内容を修正

app/views/admin/items/show.html.erb, config/locales/ja.yml
enumの日本語対応の追記をしました。
app/views/admin/items/show.html.erb
画像を選択しないで投稿するとエラー画面になったので、get_imageメソッドを使って画像を表示するように修正しました。
=> Feature add enum

app/controllers/admin/homes_controller.rb, app/controllers/public/orders_controller.rb, app/models/delivery_address.rb, app/models/item.rb, app/views/admin/homes/top.html.erb, app/views/admin/orders/show.html.erb, app/views/public/orders/new.html.erb, config/application.rb, config/locales/ja.yml, config/routes.rb
カートから注文情報入力のエラーの修正をここら見ましたが、できませんでした。
=> Feature public views orders fix

app/controllers/public/homes_controller.rb, app/controllers/public/items_controller.rb, app/views/public/homes/_genrebar.html.erb, app/views/public/homes/top.html.erb, app/views/public/items/index.html.erb, app/views/public/items/show.html.erb
・ジャンル一覧のサイドバーを部分テンプレートで作成
・topページ、商品一覧ページ、商品詳細ページに表示できるようにしました
・それに伴い各コントローラーに記述の追加や修正を行いました
・ジャンルの商品一覧ページはif文にしてpublic/items/index.html.erbに記述しました
=> ジャンル機能のview実装

app/controllers/admin/genres_controller.rb, app/controllers/admin/homes_controller.rb, app/controllers/admin/items_controller.rb
=> Fix 更新時の文言に「。」がなかったため修正

app/assets/stylesheets/public/searches.scss, app/controllers/public/searches_controller.rb, app/helpers/public/searches_helper.rb, app/models/item.rb, app/views/layouts/_header.html.erb, app/views/public/searches/_search.html.erb, app/views/public/searches/search.html.erb, config/routes.rb, test/controllers/public/searches_controller_test.rb
商品検索機能の実装を行いました。
ルーティングの追加、itemモデルに追記、コントローラとビューも追加しました。
=> Add 商品検索機能の実装

app/controllers/public/sessions_controller.rb, app/views/public/registrations/new.html.erb
=> Feature fix registration new

app/controllers/public/delivery_addresses_controller.rb, app/views/public/customers/edit.html.erb, app/views/public/delivery_addresses/edit.html.erb, app/views/public/delivery_addresses/index.html.erb
エラーメッセージを追加しました
顧客情報の編集画面と配送先住所の一覧画面、編集画面にエラーメッセージが出るように修正しました
=> エラーメッセージを追加

app/controllers/public/customers_controller.rb, app/controllers/public/delivery_addresses_controller.rb, app/controllers/public/registrations_controller.rb, app/controllers/public/sessions_controller.rb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, app/views/public/delivery_addresses/edit.html.erb, app/views/public/delivery_addresses/index.html.erb, app/views/public/homes/top.html.erb, app/views/public/registrations/new.html.erb
=> issue #79 flashメッセージを実行

app/models/item.rb
=> Feature fix get image

Gemfile, Gemfile.lock, app/controllers/public/cart_items_controller.rb, app/controllers/public/items_controller.rb, app/views/admin/customers/index.html.erb, app/views/admin/items/index.html.erb, app/views/admin/orders/index.html.erb, app/views/kaminari/_first_page.html.erb, app/views/public/cart_items/index.html.erb, app/views/public/items/index.html.erb, app/views/public/items/show.html.erb
フラッシュメッセージの実装・画像表示の修正・各ページのページネーションの修正をしました。
=> フラッシュメッセージの実装・画像表示の修正・ページネーションの修正

app/views/admin/items/show.html.erb, app/views/admin/orders/index.html.erb, app/views/admin/orders/show.html.erb
Fix もう一度ブランチを作り直して記述を修正し、リンクを追加しました。
=> Fix もう一度ブランチを作り直して記述を修正し、リンクを追加しました

config/locales/ja.yml
=> Fix 製作ステータスが日本語化されないエラーを修正

app/controllers/public/customers_controller.rb, app/controllers/public/sessions_controller.rb
ログイン後の遷移画面をマイページに修正
メールアドレスが更新できなくなっていたので修正
=> ログイン後に遷移する画面とユーザー情報の編集を修正

app/views/admin/customers/edit.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/genres/edit.html.erb, app/views/admin/genres/index.html.erb, app/views/admin/items/index.html.erb, app/views/admin/items/show.html.erb, app/views/admin/orders/index.html.erb, app/views/admin/orders/show.html.erb, app/views/public/homes/top.html.erb, app/views/public/items/index.html.erb
=> Feature layouts fix

app/views/admin/customers/edit.html.erb
レイアウトを変更しました。</br>
機能は自分でもやってみて問題なかったと思いますが、一応ご確認お願いします
イメージ</br>
=> 管理者の顧客情報編集画面を修正した
